In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [3]:
data = pd.read_excel('insurance.xlsx')

In [4]:
data

,Age,Gender,Occupation,Income,Insurance_Type,Premium_Amount,Claim_Amount
0,36,Female,Engineer,78000,Term Life Insurance,550,0
1,31,Male,Teacher,64000,Health Maintenance Organization (HMO),370,0
2,29,Female,Software Developer,88000,Comprehensive Auto Insurance,650,190
3,53,Male,Doctor,130000,Whole Life Insurance,1100,0
4,42,Female,Manager,95000,Preferred Provider Organization (PPO),450,0
...,...,...,...,...,...,...,...
881,43,Male,Marketing Executive,107000,Health Maintenance Organization (HMO),730,0
882,34,Female,Graphic Designer,82000,Whole Life Insurance,880,420
883,32,Male,Nurse,77000,Rental Car Insurance,720,0
884,31,Female,Financial Analyst,64000,Commercial Auto Insurance,690,350
885,28,Male,Engineer,67000,Disability Insurance,580,0

In [5]:
from sklearn.preprocessing import LabelEncoder

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 886 entries, 0 to 885
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             886 non-null    int64
 1   Gender          886 non-null    object
 2   Occupation      886 non-null    object
 3   Income          886 non-null    int64
 4   Insurance_Type  886 non-null    object
 5   Premium_Amount  886 non-null    int64
 6   Claim_Amount    886 non-null    int64
dtypes: int64(4), object(3)
memory usage: 48.6+ KB

In [7]:
X = data[['Age','Gender','Occupation','Income','Premium_Amount']]
y = data['Insurance_Type']

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 886 entries, 0 to 885
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             886 non-null    int64
 1   Gender          886 non-null    object
 2   Occupation      886 non-null    object
 3   Income          886 non-null    int64
 4   Insurance_Type  886 non-null    object
 5   Premium_Amount  886 non-null    int64
 6   Claim_Amount    886 non-null    int64
dtypes: int64(4), object(3)
memory usage: 48.6+ KB

In [9]:
y

0                        Term Life Insurance
1      Health Maintenance Organization (HMO)
2               Comprehensive Auto Insurance
3                       Whole Life Insurance
4      Preferred Provider Organization (PPO)
                       ...
881    Health Maintenance Organization (HMO)
882                     Whole Life Insurance
883                     Rental Car Insurance
884                Commercial Auto Insurance
885                     Disability Insurance
Name: Insurance_Type, Length: 886, dtype: object

In [10]:
encoder = LabelEncoder()
data['Gender']=encoder.fit_transform(data['Gender'])
data['Occupation']=encoder.fit_transform(data['Occupation'])
data['InsuranceType']=encoder.fit_transform(data['Insurance_Type'])
encoded_columns = ['Gender','Occupation','InsuranceType']

In [11]:
data

,Age,Gender,Occupation,Income,Insurance_Type,Premium_Amount,Claim_Amount,InsuranceType
0,36,0,3,78000,Term Life Insurance,550,0,9
1,31,1,11,64000,Health Maintenance Organization (HMO),370,0,3
2,29,0,10,88000,Comprehensive Auto Insurance,650,190,1
3,53,1,2,130000,Whole Life Insurance,1100,0,11
4,42,0,7,95000,Preferred Provider Organization (PPO),450,0,6
...,...,...,...,...,...,...,...,...
881,43,1,8,107000,Health Maintenance Organization (HMO),730,0,3
882,34,0,5,82000,Whole Life Insurance,880,420,11
883,32,1,9,77000,Rental Car Insurance,720,0,8
884,31,0,4,64000,Commercial Auto Insurance,690,350,0
885,28,1,3,67000,Disability Insurance,580,0,2

In [12]:
data.columns

Index(['Age', 'Gender', 'Occupation', 'Income', 'Insurance_Type',
       'Premium_Amount', 'Claim_Amount', 'InsuranceType'],
      dtype='object')

In [13]:
X = data[['Age','Gender','Occupation','Income','Premium_Amount']]
y = data['InsuranceType']

In [14]:
X

     Age  Gender  Occupation  Income  Premium_Amount
0     36       0           3   78000             550
1     31       1          11   64000             370
2     29       0          10   88000             650
3     53       1           2  130000            1100
4     42       0           7   95000             450
..   ...     ...         ...     ...             ...
881   43       1           8  107000             730
882   34       0           5   82000             880
883   32       1           9   77000             720
884   31       0           4   64000             690
885   28       1           3   67000             580

[886 rows x 5 columns]

In [15]:
y

0       9
1       3
2       1
3      11
4       6
       ..
881     3
882    11
883     8
884     0
885     2
Name: InsuranceType, Length: 886, dtype: int32

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [17]:
data

,Age,Gender,Occupation,Income,Insurance_Type,Premium_Amount,Claim_Amount,InsuranceType
0,36,0,3,78000,Term Life Insurance,550,0,9
1,31,1,11,64000,Health Maintenance Organization (HMO),370,0,3
2,29,0,10,88000,Comprehensive Auto Insurance,650,190,1
3,53,1,2,130000,Whole Life Insurance,1100,0,11
4,42,0,7,95000,Preferred Provider Organization (PPO),450,0,6
...,...,...,...,...,...,...,...,...
881,43,1,8,107000,Health Maintenance Organization (HMO),730,0,3
882,34,0,5,82000,Whole Life Insurance,880,420,11
883,32,1,9,77000,Rental Car Insurance,720,0,8
884,31,0,4,64000,Commercial Auto Insurance,690,350,0
885,28,1,3,67000,Disability Insurance,580,0,2

In [18]:
X_train

     Age  Gender  Occupation  Income  Premium_Amount
434   70       1           2  147000            1280
360   55       0           7  112000             670
355   40       1           1   96000             800
81    31       1          11   63000             390
838   62       0           5   98000            1230
..   ...     ...         ...     ...             ...
106   28       0          10   88000             660
270   49       0           4  108000             690
860   33       0           0   73000             680
435   56       0           7  113000             680
102   42       0           4  102000             600

[708 rows x 5 columns]

In [19]:
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [20]:
predictions = model.predict(X_test)

In [21]:
accuracy = accuracy_score(y_test, predictions)
print(f"Accuracy: {accuracy}")

Accuracy: 0.9943820224719101

In [22]:
def recommend_insurance(customer_data, model, encoder, encoded_columns):
    customer_data_encoded = pd.DataFrame()
    for col in customer_data.columns:
        if col in encoded_columns:
            customer_data_encoded[col] = encoder.fit_transform(customer_data[col])
        else:
            customer_data_encoded[col] = customer_data[col]
    
    probabilities = model.predict_proba(customer_data_encoded)
    top_3_indices = (-probabilities).argsort()[:, :3]
   
    
    return top_3_indices

In [23]:
new_customer_data = pd.DataFrame({
    'Age': [35],
    'Gender': ['Female'],
    'Occupation': ['Teacher'],
    'Income': [54000],
    'Premium_Amount': [490]
})

In [24]:
recommendations = recommend_insurance(new_customer_data,model, encoder,encoded_columns)
print("Recommended Insurance Types:", recommendations)

Recommended Insurance Types: [[5 9 2]]

In [25]:
def inverse_type(top_3_indices):
    for i in range(3):
        top_3_insurance_types = encoder.inverse_transform([top_3_indices[i]])
        print(top_3_insurance_types)

In [26]:


data

,Age,Gender,Occupation,Income,Insurance_Type,Premium_Amount,Claim_Amount,InsuranceType
0,36,0,3,78000,Term Life Insurance,550,0,9
1,31,1,11,64000,Health Maintenance Organization (HMO),370,0,3
2,29,0,10,88000,Comprehensive Auto Insurance,650,190,1
3,53,1,2,130000,Whole Life Insurance,1100,0,11
4,42,0,7,95000,Preferred Provider Organization (PPO),450,0,6
...,...,...,...,...,...,...,...,...
881,43,1,8,107000,Health Maintenance Organization (HMO),730,0,3
882,34,0,5,82000,Whole Life Insurance,880,420,11
883,32,1,9,77000,Rental Car Insurance,720,0,8
884,31,0,4,64000,Commercial Auto Insurance,690,350,0
885,28,1,3,67000,Disability Insurance,580,0,2

In [27]:
data['Insurance_Type'].unique()

array(['Term Life Insurance', 'Health Maintenance Organization (HMO)',
       'Comprehensive Auto Insurance', 'Whole Life Insurance',
       'Preferred Provider Organization (PPO)',
       'Third Party Liability Auto Insurance', 'Disability Insurance',
       'Long-Term Care Insurance', 'Rental Car Insurance',
       'Professional Liability Insurance',
       'Medicare Supplement Insurance', 'Commercial Auto Insurance'],
      dtype=object)

In [28]:
import numpy as np
y_1d = np.ravel(recommendations)

In [29]:
def inverse_type(y_1d):
    for i in range(3):
        income_of_doctors = data.loc[data['InsuranceType'] == y_1d[i], 'Insurance_Type'].iloc[0]
        print(income_of_doctors)

In [30]:
inverse_type(y_1d)

Medicare Supplement Insurance
Term Life Insurance
Disability Insurance

In [34]:
import pickle 
with open('insurance_recommendation.pkl', 'wb') as model_file:
    load_model=pickle.dump(model, model_file)

In [35]:
load_model.predict([[78,0,1,90000000,1000]])

AttributeError: 'NoneType' object has no attribute 'predict'

In [32]:
predictions = model.predict([[78,0,1,90000000,1000]])

c:\Users\lavan\anaconda\lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(